apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    sidecarInjector:
      enabled: true
    citadel:
      enabled: true

  values:
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true